// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: init.sql

package database

import (
	"context"
)

const createChangesTable = `-- name: CreateChangesTable :exec
CREATE TABLE IF NOT EXISTS changes (
    id INTEGER PRIMARY KEY,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    change_time TEXT NOT NULL,
    notes TEXT
)
`

func (q *Queries) CreateChangesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createChangesTable)
	return err
}

const createProfilesTable = `-- name: CreateProfilesTable :exec
CREATE TABLE IF NOT EXISTS profiles (
    id INTEGER PRIMARY KEY,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    baby_name TEXT NOT NULL,
    baby_birthday TEXT NOT NULL,
    diaper_interval_minutes INTEGER
)
`

func (q *Queries) CreateProfilesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createProfilesTable)
	return err
}
