// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Change struct {
	ID         int64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	ChangeTime string
	Notes      sql.NullString
}

type Profile struct {
	ID                    int64
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
	BabyName              string
	BabyBirthday          string
	DiaperIntervalMinutes sql.NullInt64
}
